<?php

	if( function_exists('acf_add_local_field_group') ):

		global $animate_css;

		acf_add_local_field_group(array (
			'key' => 'theme_settings_email_group',
			'title' => 'Theme Settings - Email',
			'fields' => array (
				array (
					'key' => 'field_5873a3fe481cd',
					'label' => 'Header del email',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_5873a33f3b438',
					'label' => 'Logo para email',
					'name' => 'theme_settings_email__logo',
					'type' => 'image',
					'instructions' => 'Logo para email (Si no se escoge una imagen, recogerá el logo principal)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5873a434481cf',
					'label' => 'Logo width',
					'name' => 'theme_settings_email__logo_width',
					'type' => 'number',
					'instructions' => 'Tamaño de ancho para el logo del email (por defecto 200px)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array (
					'key' => 'field_5873a47c590a4',
					'label' => 'From email',
					'name' => 'theme_settings_email__from_email',
					'type' => 'email',
					'instructions' => 'From email',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_5873a514590a5',
					'label' => 'Bcc emails',
					'name' => 'theme_settings_email__bcc_email',
					'type' => 'text',
					'instructions' => 'Bcc emails, separados por \',\'',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a414481ce',
					'label' => 'Footer del email',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_5873a56785a49',
					'label' => 'Añadir redes sociales en email',
					'name' => 'theme_settings_email__social_networks_in_mail',
					'type' => 'true_false',
					'instructions' => 'Añadir redes sociales en email (Marcado: Sí)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_5873a5c085a4a',
					'label' => 'Copyright en email',
					'name' => 'theme_settings_email__copyright',
					'type' => 'text',
					'instructions' => 'Copyright que aparecerá en email',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Copyright (c) [year] [company]',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a62379735',
					'label' => 'Colores del email',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_5873a63979736',
					'label' => 'Color de fondo - Email',
					'name' => 'theme_settings_email__email_bg_color',
					'type' => 'color_picker',
					'instructions' => 'Color de fondo - Email',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#EFEFEF',
				),
				array (
					'key' => 'field_5873a68279737',
					'label' => 'Color de fondo - Header',
					'name' => 'theme_settings_email__header_bg_color',
					'type' => 'color_picker',
					'instructions' => 'Color de fondo - Header',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#557DA1',
				),
				array (
					'key' => 'field_5873a6d179739',
					'label' => 'Color de texto - Header',
					'name' => 'theme_settings_email__header_text_color',
					'type' => 'color_picker',
					'instructions' => 'Color de texto - Header',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
				),
				array (
					'key' => 'field_5873a6bb79738',
					'label' => 'Color de fondo - Body',
					'name' => 'theme_settings_email__body_bg_color',
					'type' => 'color_picker',
					'instructions' => 'Color de fondo - Body',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#FFFFFF',
				),
				array (
					'key' => 'field_5873a6f37973a',
					'label' => 'Color de texto - Body',
					'name' => 'theme_settings_email__body_text_color',
					'type' => 'color_picker',
					'instructions' => 'Color de texto - Body',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000000',
				),
				array (
					'key' => 'field_5873a7087973b',
					'label' => 'Color de texto - Footer',
					'name' => 'theme_settings_email__footer_text_color',
					'type' => 'color_picker',
					'instructions' => 'Color de texto - Footer',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000000',
				),
				array (
					'key' => 'field_5873a74a7973d',
					'label' => 'Previsualizar',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_5873a7537973e',
					'label' => 'Previsualizar',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options-email',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
			'modified' => 1484066150,
			'local' => 'json',
		));

		acf_add_local_field_group(array (
			'key' => 'theme_settings_general_group',
			'title' => 'Theme Settings - General',
			'fields' => array (
				array (
					'key' => 'field_58739ff13eb60',
					'label' => 'Logo principal',
					'name' => 'theme_settings_general__logo',
					'type' => 'image',
					'instructions' => 'Logo principal de la web',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5873a03d3eb62',
					'label' => 'Logo Alternativo',
					'name' => 'theme_settings_general__logo_alt',
					'type' => 'image',
					'instructions' => 'Logo alternativo de la web',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5873a0833eb63',
					'label' => 'Favicon',
					'name' => 'theme_settings_general__favicon',
					'type' => 'image',
					'instructions' => 'Logo alternativo de la web',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5873a0b92cf30',
					'label' => 'Teléfono de empresa',
					'name' => 'theme_settings_general__phone',
					'type' => 'text',
					'instructions' => 'Teléfono de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a0e32cf31',
					'label' => 'Email de empresa',
					'name' => 'theme_settings_general__mail',
					'type' => 'email',
					'instructions' => 'Email de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_5873b3cb017fc',
					'label' => 'Google Analytics de la web',
					'name' => 'theme_settings_general__google_analytics',
					'type' => 'textarea',
					'instructions' => 'Google Analytics de la web (con el tag script también)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array (
					'key' => 'field_5873a1292cf33',
					'label' => 'Imagen de fondo de login',
					'name' => 'theme_settings_general__login_bg_image',
					'type' => 'image',
					'instructions' => 'Imagen de fondo de login',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5873a1522cf34',
					'label' => 'Imagen de fondo de registro',
					'name' => 'theme_settings_general__register_bg_image',
					'type' => 'image',
					'instructions' => 'Imagen de fondo de registro',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options-general',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
			'modified' => 1484059725,
			'local' => 'json',
		));

		acf_add_local_field_group(array (
			'key' => 'theme_settings_header_group',
			'title' => 'Theme Settings - Header',
			'fields' => array (
				array (
					'key' => 'field_583710a56bf65',
					'label' => 'Animación para el header',
					'name' => 'theme_settings_header__animation_header',
					'type' => 'select',
					'instructions' => 'Animación para el header',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => $animate_css,
					'default_value' => array (
						0 => 'fadeInDown',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 1,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_587663f96303d',
					'label' => 'Header Menú: Manera de mostrar submenú (Opciones)',
					'name' => '',
					'type' => 'tab',
					'instructions' => 'Header Menú : Manera de mostrar submenú (horizontal o vertical)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_587661f3f9cb3',
					'label' => 'Desplegar (horizontal o vertical)',
					'name' => 'theme_settings_header__header_menu_display_type',
					'type' => 'select',
					'instructions' => 'Desplegar (horizontal o vertical)',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'inline' => 'En línea',
						'vertical' => 'Vertical',
					),
					'default_value' => array (
						0 => 'vertical',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_587666326303e',
					'label' => 'Posición (izquierda o auto)',
					'name' => 'theme_settings_header__header_menu_position',
					'type' => 'select',
					'instructions' => 'Posición (izquierda o auto)
		- Left: mostrar el submenú desde la posición mas a la izquierda posible.
		- Auto: mostrar el submenu desde la posicion relativa al elemento padre.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Izquierda',
						'auto' => 'Auto',
					),
					'default_value' => array (
						0 => 'auto',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_587666aa16df3',
					'label' => 'Animación (Tipo de animación al aparecer el elemento)',
					'name' => 'theme_settings_header__header_menu_animation_type',
					'type' => 'select',
					'instructions' => 'Animación (Tipo de animación al aparecer el elemento)',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'menu-1' => 'Tipo 1',
						'menu-2' => 'Tipo 2',
						'menu-3' => 'Tipo 3',
						'menu-4' => 'Tipo 4',
						'menu-5' => 'Tipo 5',
					),
					'default_value' => array (
						0 => 'menu-1',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_58999bceb0c1d',
					'label' => 'Tipo de animación para el botón de mostrar "menu mobile" (Toggle)',
					'name' => 'theme_settings_header__header_button_toggle_animation_type',
					'type' => 'select',
					'instructions' => 'Tipo de animación para el botón de mostrar "menu mobile" (Toggle)',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						1 => 'Animación 1',
						2 => 'Animación 2',
						3 => 'Animación 3',
						4 => 'Animación 4',
						5 => 'Animación 5',
						6 => 'Animación 6',
						7 => 'Animación 7',
						8 => 'Animación 8',
						9 => 'Animación 9',
						10 => 'Animación 10',
						11 => 'Animación 11',
						12 => 'Animación 12',
					),
					'default_value' => array (
						0 => 6,
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options-header',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
			'modified' => 1484154873,
			'local' => 'json',
		));

		acf_add_local_field_group(array (
			'key' => 'theme_settings_social_group',
			'title' => 'Theme Settings - Social',
			'fields' => array (
				array (
					'key' => 'field_5873a1f993d23',
					'label' => 'Facebook',
					'name' => 'theme_settings_social__facebook',
					'type' => 'text',
					'instructions' => 'Link de facebook de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a25193d24',
					'label' => 'Twitter',
					'name' => 'theme_settings_social__twitter',
					'type' => 'text',
					'instructions' => 'Link de twitter de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a28e65d01',
					'label' => 'Google+',
					'name' => 'theme_settings_social__google',
					'type' => 'text',
					'instructions' => 'Link de google+ de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a29665d02',
					'label' => 'Linkedin',
					'name' => 'theme_settings_social__linkedin',
					'type' => 'text',
					'instructions' => 'Link de linkedin de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a29765d03',
					'label' => 'Instagram',
					'name' => 'theme_settings_social__instagram',
					'type' => 'text',
					'instructions' => 'Link de instagram de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a29865d04',
					'label' => 'Pinterest',
					'name' => 'theme_settings_social__pinterest',
					'type' => 'text',
					'instructions' => 'Link de pinterest de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a29965d05',
					'label' => 'Youtube',
					'name' => 'theme_settings_social__youtube',
					'type' => 'text',
					'instructions' => 'Link de youtube de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5873a2ea65d06',
					'label' => 'Tripadvisor',
					'name' => 'theme_settings_social__tripavisor',
					'type' => 'text',
					'instructions' => 'Link de tripadvisor de empresa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options-social',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
			'modified' => 1484059727,
			'local' => 'json',
		));

	endif;

